### ISSUE TITLE
Feature request for free corner crop.

### ISSUE THREAD

**Issue by rvenky125** [SmartToolFactory/Compose-Cropper#1]
Thanks for lib. It's very useful. It would be nice to add free corner crop like in CamScanner.
![Screenshot_2022-10-08-07-23-30-52_680d03679600f7af0b4c700c6b270fe7](https://user-images.githubusercontent.com/58197145/194682260-ab2c62af-df8d-42e8-a79a-6f4501bce566.jpg)

**Comment by SmartToolFactory** [comment]
Doesn't dynamic crop type does this? You can move handles to shrink or expand crop area or move overlay if you touch inside overlay area but not handles?

**Comment by SmartToolFactory** [comment]
After checking again i see that it doesn't resemble to dynamic type. It require handles that can change path. I think i should add this feature to freehand crop which should have drawing by moving pointer, erasing, drawing shapes or lines and shapes that can  be adjusted via handles.

**Comment by rvenky125** [comment]
Yes it should be added like a new feature. I've tried to do that by forking your repo. But I failed. I'm glad to get help from you. Thank you ☺️

**Comment by rvenky125** [comment]
Hi @SmartToolFactory , is there any update?

**Comment by T8RIN** [comment]
Will it be added? :(

**Comment by SmartToolFactory** [comment]
I might but i'm busy with full-time work at the moment. I have more plans for image, zoom and crop libraries but might take awhile.

**Comment by T8RIN** [comment]
Alright, good luck, thanks for your hard work!
