### ISSUE TITLE
Can I change the background color of the cropper?

### ISSUE THREAD

**Issue by dylan-kwon** [SmartToolFactory/Compose-Cropper#10]
I want to change the color of the black background in the photo.

![KakaoTalk_Photo_2023-01-05-10-21-46](https://user-images.githubusercontent.com/21299684/210680403-861c81c1-0316-4618-ab5a-28bf2f4aa938.jpeg)

**Comment by antonb03** [comment]
This issue is similar https://github.com/SmartToolFactory/Compose-Cropper/issues/7

**Comment by wikikhtn** [comment]
It's solved in [PR](https://github.com/SmartToolFactory/Compose-Cropper/pull/28)
This issue should be closed.
