### ISSUE TITLE
Crop area is not respected for the 9:16 ratio

### ISSUE THREAD

**Issue by antonb03** [SmartToolFactory/Compose-Cropper#21]
Looks like there is a bug. 
Steps to reproduce on Demo app:
1. Select a 9:16 ratio
2. Select an image from the gallery
3. Press crop without taking any actions

Actual: The image is not cropped properly
Expected: The image is cropped according to the area selected

I notice that if I move the image a little bit it crops properly, the issue happens only if the user selected the image and takes no action to adjust the crop area

Video of the bug
https://github.com/SmartToolFactory/Compose-Cropper/assets/11620779/a4bf603f-a9e2-49e4-8afe-c7b1ce1d15f7

**Comment by SmartToolFactory** [comment]
This issue is fixed in 0.4.0
