### ISSUE TITLE
Versions 0.3.1, 0.3.2 & 0.3.3 are unavailable from Jitpack due to build failures

### ISSUE THREAD

**Issue by sebj** [SmartToolFactory/Compose-Cropper#22]
Versions 0.3.1, 0.3.2, and 0.3.3, which have been tagged on Github, seem to be [unavailable from Jitpack.io](https://jitpack.io/#SmartToolFactory/Compose-Cropper). The main error in the build logs there seems to be: `Could not resolve com.android.tools.build:gradle:8.0.0.`.

**Comment by SmartToolFactory** [comment]
@Nimrodda fixed this issue. Starting with 0.3.4 you can, again, use jitpak.io versions to import project.

**Comment by sebj** [comment]
Great, thanks!
