### ISSUE TITLE
How Can I Add a compose to the Crop Position?

### ISSUE THREAD

**Issue by CharlesMoreira1** [SmartToolFactory/Compose-Cropper#33]
Hi! I just started exploring your library, and I find it great with many possible customizations!

But I have a question...

I would like to get the crop position and add a tooltip or tip on top. Is there a way for me to implement this?

**Comment by SmartToolFactory** [comment]
Hi, Thanks. What do you mean by crop position? Do you wish to get bounding rectangle of crop area or overlay on composable? These are different since screen size and image size might not be equal.

**Comment by CharlesMoreira1** [comment]
So, I would like to add a compose, right above where I highlighted.

Example: 
![Screenshot_2023-11-25-07-56-33-110_com google android googlequicksearchbox](https://github.com/SmartToolFactory/Compose-Cropper/assets/55266908/dba906f7-b0ba-433c-9b67-b53e73d0ce1e)
