### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Pantsoffski** [SmartToolFactory/Compose-Cropper#37]
Great library with great potential, but the lack of any documentation makes using it very difficult. I also see that it is probably no longer supported by the author.

**Comment by SmartToolFactory** [comment]
You can check out demos. I'm supporting it but i'm not available for the time being. Full time work unfortunately but i review and merge PRs.

**Comment by jiangdi0924** [comment]
It does need documentation, the demo code is not very easy to use. Thanks to the author for his contribution!👍
