### ISSUE TITLE
Remove Offset in Static crop type

### ISSUE THREAD

**Issue by ceyton** [SmartToolFactory/Compose-Cropper#4]
Is it possible to remove the Offset in the Static crop type?

![image](https://user-images.githubusercontent.com/71691261/194778121-230666d3-ca7f-4de5-96e6-46e50d3962db.png)

**Comment by SmartToolFactory** [comment]
Other croppers have this offset too. I will add option to set zoom to match drawing area to be able to crop with no offset on any sides if needed

**Comment by ceyton** [comment]
> Other croppers have this offset too but i can add a flag to remove offset. Also i think i should adjust zoom to be less than 1f match drawing area to be able to crop with no offset on any sides if needed.

in most cases, I think of, I don't think that scale should be less than 1f, regarding the offset I was trying to implement Instagram-like cropping this is why it would really be nice to have it without the crop 👍

**Comment by SmartToolFactory** [comment]
Overlay ratio option in settings menu can scale overlay between 50 and 100%.

![overlay_ratio](https://user-images.githubusercontent.com/35650605/195991975-ddb8568a-9e83-42b9-a100-17e3ce4e9413.png)
