### ISSUE TITLE
Avoid empty spaces

### ISSUE THREAD

**Issue by carlosgasa** [SmartToolFactory/Compose-Cropper#5]
Is there any way to avoid blank spaces?, that the drag limit is the image

Thanks!

![photo_2022-10-13_11-04-20](https://user-images.githubusercontent.com/25380778/195648053-3a6508d9-fa7a-463a-aec3-2038de250bd8.jpg)

**Comment by SmartToolFactory** [comment]
This is issue #4 . I will add option to scale between 50-100% of the smaller dimension of screen on next update. Coefficient in CropState is set for this, i will make it public and adjustable in settings section since it effects state itself instead of just being cosmetic change

**Comment by carlosgasa** [comment]
> This is issue #4 . I will add option to scale between 50-100% of the smaller dimension of screen on next update. [Coefficient in CropState](https://github.com/SmartToolFactory/Compose-Cropper/blob/f68e66d4677d81fd3bb42ecca2e140625c1f1512/cropper/src/main/java/com/smarttoolfactory/cropper/state/CropStateImpl.kt#L388) is set for this, i will make it public and adjustable in settings section since it effects state itself instead of just being cosmetic change

Thanks, I believe that is it

![image](https://user-images.githubusercontent.com/25380778/195656992-bf62bc91-3435-40a0-8cbc-ac13ef960b39.png)

**Comment by SmartToolFactory** [comment]
I haven't implemented limitPan yet, i need to finish rotation first. It might be very difficult to limit pan area when image is rotatable. My zoom and image libraries have this option but rotating by any angle is quite complicated. I might not implement it either. For now image should animate back to valid bounds whether fling is enabled or not. 

https://stackoverflow.com/questions/16702966/rotate-image-and-crop-out-black-borders

**Comment by SmartToolFactory** [comment]
Also i need to change zoom focus from center of the image to center of pointers. In Compose it adds another layer of complexity. I will go back to these features when i iron out some bugs and finish freehand crop. Then i might think throughly for these complex features

**Comment by carlosgasa** [comment]
> Also i need to change zoom focus from center of the image to center of pointers. In Compose it adds another layer of complexity. I will go back to these features when i iron out some bugs and finish freehand crop. Then i might think throughly for these complex features

I understand, thanks for the support <3
